##
## application.yml — главный конфигурационный файл Spring Boot.
#
#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.
server:
  servlet:
    context-path: /api
  port: ${SERVER_PORT:8080}   # значение по умолчанию 8080, если переменная не задана

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bankcards_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      write-dates-as-timestamps: false

  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml
    enabled: true

jwt:
  secret: ${JWT_SECRET:85cd200f70bc9802fea817ff6ccd46722bfa3201f32560430154c6cafa940de2}
  expiration: ${JWT_EXPIRATION:3600000}

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  config: classpath:logback-spring.xml


